### ISSUE TITLE
US01 - Registrar informações dos usuários

### ISSUE THREAD

**Issue by guiaugusto** [fga-eps-mds/2018.2-Lino#103]
US01 - Eu, como usuário, desejo ser notificado sobre o cardápio diário do RU para me informar

**Descrição**

Existe uma grande necessidade de registrar, no banco de dados, os usuários que fazem uso do Lino, pois é de grande importância que se mantenha suas informações para o envio de notificações no geral.

**Tarefas**

- [x] Criar action que, no envio da primeira mensagem ao bot, o usuário seja cadastrado
- [x] Criar método geral para cadastrar na lista de cada notificação a cada novo usuário que deseja recebê-la

**Critérios de Aceitação**

- [x] Os usuários devem estar registrados no banco de dados
- [x] A lista de determinada notificação deve ser incrementada automaticamente a cada novo usuário
- [x] A mensagem do cardápio deve ser enviada à todos que desejam recebê-la

**Comment by guilhesme23** [comment]
Foram criadas uma action que salva o usuário no banco de dados, e uma action que salva esse usuário em uma lista de usuários que desejam receber notificações.
