### ISSUE TITLE
US01 - Criar agendamento para envio do cardápio

### ISSUE THREAD

**Issue by guiaugusto** [fga-eps-mds/2018.2-Lino#104]
US01 - Eu, como usuário, desejo ser notificado sobre o cardápio diário do RU para me informar

**Descrição**

Realizar o agendamento do envio do cardápio aos usuários, informando-os, em um horário determinado.

**Tarefas**

- [x] Criar um cron para script de envio das notificações do cardápio em um horário específico
- [x] Generalizar a criação do cron para os demais agendamentos

**Critérios de Aceitação**

- [x] O usuário deve receber a notificação no horário especificado no cron

**Comment by guilhesme23** [comment]
Depois de um tempo apanhando pro cron, conseguimos descobrir o erro e fazer funcionar rodando um bash script que roda o script de notificação.
