### ISSUE TITLE
Testar API RU/Crawler

### ISSUE THREAD

**Issue by icarooliv** [fga-eps-mds/2018.2-Lino#110]
**Descrição**
Realizar testes unitários no serviço do RU/WebCrawler. 

**Tarefas**

- [x] Utilizar Pytest

- [x] Testar as Controllers e os Endpoints

- [x] Mockar os dados possíveis para garantir a integridade dos testes

**Critérios de Aceitação**

- [x] 60% de cobertura total

**Comment by guilhesme23** [comment]
Durante a realização dos testes foi percebido que a complexidade do código está muito alta, devido a quantidade excessiva de validações a cada requisição. Isso acontece pelo fato de o código ainda não se comunicar com o banco de dados, tendo então que realizar diversas operações com arquivos no disco rígido. Visto que isso deveria ser refatorado futuramente e geraria impacto nos testes feitos para os métodos como estão agora, o melhor seria refatorar o código para que utilizasse o banco de dados antes que fossem feitos os testes.

**Comment by guilhesme23** [comment]
Esta issue poderá ser realizada após ser feita a issue #131
