### ISSUE TITLE
Verificar disponibilidade do Banco de Dados

### ISSUE THREAD

**Issue by icarooliv** [fga-eps-mds/2018.2-Lino#112]
**Descrição**

Conforme foi notado essa semana, o firewall da UnB bloqueia acessos ao mLab, que era nossa opção para os bancos na nuvem. O objetivo é buscar e implementar alternativas para isso.

**Tarefas**

- [x] Identificar se há possibilidade de continuar utilizando o mLab

- [x] Verificar se há disponibilidade deles quando conectados à rede da UnB

**Critérios de Aceitação**

 - [x] Disponibilizar acesso aos bancos

**Comment by brunapinos** [comment]
@guiaugusto Qual é a situação dessa issue? Algum problema enfrentado?

**Comment by guiaugusto** [comment]
Após essa análise, acabamos percebendo a necessidade da criação de um ambiente de desenvolvimento e um ambiente de produção  que esteja bem documentada para uma melhor utilização e também permitir acesso a comunidade de contribuidores externos.
