### ISSUE TITLE
US10 - Receber Email do servidor 

### ISSUE THREAD

**Issue by icarooliv** [fga-eps-mds/2018.2-Lino#114]
**Descrição**

O Lino deve realizar requisições para a API de Alertas, através da sua API para verificar se há algum e-mail recente. 

**Tarefas**
- [x] Realizar o cronjob para requisitar a cada 5s se há um e-mail recente. 

- [x] Verificar se o e-mail é enviado para os usuários

**Critérios de Aceitação**

- [x] Enviar o alerta aos usuários do bot

**Comment by MatheusBlanco** [comment]
Estivemos tendo dificuldades no entendimento geral da Issue, o que já foi clarificado graças à ajuda do @icarooliv , além de dificuldades de entendimento e aplicação do cronjob de maneira que faça a verificação de e-mails em determinado tempo e problemas de entendimento em como subir o ambiente para desenvolvimento e testes.
