### ISSUE TITLE
Intent_02 - Obter cardápio do dia - Telegram

### ISSUE THREAD

**Issue by icarooliv** [fga-eps-mds/2018.2-Lino#115]
**Descrição**
Montar o fluxo utilziando a personalidade do Lino para direcionar o usuário a obter o cardápio diário

**Tarefas**

- [x] Aplicar personalidade do Lino nos textos
- [x] Criar entidades relacionadas ao período do cardápio

**Critérios de Aceitação**
- [ ] O usuário consegue visualizar o cardápio diário requisitado

**Comment by brunapinos** [comment]
@leticiadesouza @pedro-prp qual é a situação?

**Comment by pedro-prp** [comment]
Fiquei totalmente sem ação nessa Issue, a questão que realmente bateu foi a má interpretação do rasa com as intents. Acabei ficando dependente do Blanco consertar o fluxo que havia sido feito na sprint anterior, o que retornou num não avanço dessa issue.
