### ISSUE TITLE
[Task 2 e 3] US01 - Registrar usuários dos mensageiros que desejam receber a notificação do cardápio diário

### ISSUE THREAD

**Issue by leticiadesouza** [fga-eps-mds/2018.2-Lino#123]
US01 - Registrar usuário, do Telegram e do Messenger que queria receber a notificação do cardápio diário, no banco de dados

**Descrição**
Registrar os usuários que utilizam dos mensageiros (Telegram e Messenger), que desejam optar por receber a notificação do cardápio diário, através do salvamento no banco de dados.

**Tarefas**

- [x] Testar a viabilidade da obtenção de dados do usuário no Telegram 
- [x] Testar a viabilidade da obtenção de dados do usuário no Messenger
- [x] Diferenciar os ids dos usuários para separá-los nos bancos específicos de cada mensageiro

**Critérios de Aceitação**

- [x] Ter os usuários que optaram por receber a notificação do cardápio registrados nos bancos específicos de cada mensageiro.

**Comment by guiaugusto** [comment]
Como já havia feito anteriormente, e organizado pelo @pedro-prp , a viabilidade da obtenção dos dados no telegram foi testada e o processo de registro dos usuários no telegram foi feita.

No _Messenger_, nosso maior problema fazer o fluxo incrementar parte de alguma custom_action. Depois de testarmos diversos procedimentos, não conseguimos fazer ele realizar esse processo. 

Testamos nas seguintes formas:

* Tentando refatorar a train-messenger.py para conseguir classificar corretamente, tentando também fazer com que entre nas custom_actions do bot. RESULTADO: Conversa, classifica razoavelmente, porém não entra em nenhuma custom_action

* Utilizando o conector recomendado pela própria documentação do Rasa. RESULTADO: Não entra em nenhum fluxo. O Bot recebe a mensagem mas não responde de forma alguma.

Logo, não conseguimos fazer as tasks dependentes a isso.

**Comment by guiaugusto** [comment]
Conseguimos mitigar o problema de não entrar nas custom actions.

Por falta de maturidade da dupla, não conseguimos seguir corretamente o fluxo de conversa que leva à alguma custom action pra teste, mas finalizamos esse problema, criando também um fluxo provisório para a action que cadastra os usuários, onde modularizamos e onde ainda estamos organizando para identificar qual mensageiro utilizado pelo usuário.

De resto, só falta fechar essa action, validar entre a dupla, e partir para a separação dos tipos de notificação existentes, criando uma lista para cada e cadastrando o usuário que desejar recebê-la.
