### ISSUE TITLE
[Task 1] I07 - Tirar dúvida sobre o período de matrícula

### ISSUE THREAD

**Issue by leticiadesouza** [fga-eps-mds/2018.2-Lino#126]
Task 1 - Fazer o webcrawler pegar o PDF corretamente 

**Descrição**
Criar um webcrawler que consiga recuperar o PDF que contém o calendário de matrículas no site do SAA.

**Tarefas**
- [x] Criar um spider para pegar o PDF do calendário no site do SAA

**Critérios de Aceitação**

- [x] Obter PDF com o calendário de matrículas

**Comment by pedro-prp** [comment]
Foi utilizado um **if** que pode ter ficado um tanto confuso no código, ele serve para corrigir um erro que se obtém ao extrair uma das urls dos pdfs. Ele se encontra no "scraper.py" e tem essa aparência:

````
if "%09" in item['url']:
                url = item['url'].replace("%09","")
````
Ao perceber a presença do **"%09"** indesejado para a url, a função replace realiza a retirada do mesmo da string em questão.

(link direto para a linha de código em que há a ocorrência do **if**)
https://github.com/BotLino/Lino-Webcrawler-Matricula/blob/38336e876695234bff270e82a26a6fe5c20f83c1/crawler/scraper.py#L35
