### ISSUE TITLE
Refatorar código do Webcrawler-RU

### ISSUE THREAD

**Issue by guilhesme23** [fga-eps-mds/2018.2-Lino#131]
Refatoração do código do Crawler do RU

**Descrição**

O código do webcrawler ainda não está se comunicando com o banco de dados, tudo está sendo salvo em arquivos locais pelo fato de no momento da criação do código ainda não havia um banco para ser utilizado. A medida que o código foi evoluindo a complexidade e a quantidade de acessos ao disco começaram a impactar na performance do código gerando a necessidade de alterar a lógica dos métodos para que acessem o banco que agora já esta disponível.

**Tarefas**
- [x] Criar um ambiente de desenvolvimento com o banco de dados
- [x] Criar uma estratégia para o armazenamento das datas
- [x] Alterar os métodos para salvar os arquivos no banco de dados
- [x] Buscar os dados diretamente no banco

**Critérios de Aceitação**
- [x] O código está passando pelo flake8
- [x] Os crawler está buscando as informações no banco de dados

**Comment by guiaugusto** [comment]
Como a branch relativa a issue foi merjada na devel e documentada, estou fechando a issue aqui
