### ISSUE TITLE
Proposta de refatoração do Lino-alerta

### ISSUE THREAD

**Issue by gabrielfilipe7unb** [fga-eps-mds/2018.2-Lino#138]
<h1>SUGESTÃO</h1> 

Pessoal, conversando em uma bela tarde com o meu amigo Guilherme Augusto tivemos um brainstorm a respeito de nossa API de Alertas. 

Primeiramente, notamos que ainda não estava tão claro como funcionaria o recebimento dos alertas pelas plataformas de mensagens em que estamos trabalhando. Isso em consequência de possuirmos uma lista de mais de 100 e-mails e, ainda assim, haver a possibilidade de o usuário lidar com um baita flood no seu chat.

Estou abrindo essa issue para nós discutirmos melhor essa funcionalidade afim de deixarmos mais claro a solução para tal problemática.

- De primeira viajem, tenho alguns tópicos a serem levados em consideração:

Como temos uma quantidade de usuários muito grande, talvez seja uma opção considerarmos uma quantidade limite de alertas mensal (ou semestral) para cada professor, assim, teríamos um controle maior sobre a quantidade total de alertas. Porém, considerando, por exemplo, que cada professor tenha direito a fazer 2 alertas mensais e que, no pior cenário, todos os professores mandem os 2 alertas, teremos ainda mais de 200 e-mails. Para o usuário receber essa penca de alertas seria ainda muito ruim.

Tendo em vista isso, uma outra opção seria liberar apenas um e-mail de alerta por mês e, caso o professor tenha a necessidade de mandar mais de um, seja feita uma solicitação para isso. Neste caso, talvez teríamos que fazer um fluxo de solicitação de envio de mais mensagens a mais.

Existe, também, a possibilidade de deixar com que o usuário escolha de quais professores deseja receber o alerta. Mas, isso talvez seja muito complexo para o desenvolvimento tendo em vista o prazo de entrega do projeto.

No mais é isso, bora trabalhar!

**Comment by icarooliv** [comment]
Não vimos necessidade devido ao fluxo de mensagens ser baixo, geraria dificuldade técnica e preferimos focar na melhoria de outros serviços em detrimento a este.
