### ISSUE TITLE
Criar templates de testes de usabilidade

### ISSUE THREAD

**Issue by icarooliv** [fga-eps-mds/2018.2-Lino#141]
**Descrição**

Uma vez que o bot já possui integração com outros serviços e estabilidade para fluxos completos, além dos serviços possuírem testes unitários vê-se a necessidade de testes de usabilidade, que servirão para reconhecer e, consequente, mitigar os erros não encontrados em etapas anteriores. 

Esses testes poderão ser executados com potenciais usuários do bot que não necessariamente são da equipe, garantindo que não existirá algum viés dos responsáveis pelo desenvolvimento do produto.

**Tarefas**

- [x] Definir os fluxos para cada ator, que podem ser incrementados com o decorrer do desenvolvimento do produto
- [x] Definir regras para o ambiente de teste
- [x] Definir os critérios de aceitação e notas para cada coleta de métricas de usabilidade
- [x] Realizar teste piloto com a equipe de desenvolvimento 

**Critérios de Aceitação**

- [x] Aceitação de versão estável para os _templates_ pela equipe

**Comment by icarooliv** [comment]
Logo ao criar essa issue, percebi que seria interessante utilizarmos o Google Forms para coletar métricas interessantes que encontrei em uma pesquisa rápida. São elas:

**Desempenho**: Quanto tempo e quantos passos são necessários para que a pessoa complete tarefas básicas?
**Precisão**: Quantos erros a pessoa cometeu? E eles foram fatais ou a pessoa conseguiu se recuperar com as informações recebidas pelo sistema?
**Lembrança**: O quanto a pessoa se lembra mais tarde ou depois de períodos sem usar?
**Resposta emocional**: Como a pessoa se sentiu depois de completar a tarefa? A pessoa estava confiante ou estressada? Ela recomendaria o produto a um amigo?

Além dessas, podemos "emular" algumas das métricas que havíamos planejado anteriormente com o uso do Elasticsearch, que foi preterido em razão de melhorar a documentação do RASA.

O que acham?

Fonte: https://www.caelum.com.br/apostila-ux-usabilidade-mobile-web/usabilidade/#o-que--medido

**Comment by brunapinos** [comment]
@icarooliv Acho interessante. Usamos algo parecido com a Tais, mas não era um forms, e sim uma planilha em que os moderadores anotavam durante o teste. Porém, o uso do forms pode facilitar

**Comment by icarooliv** [comment]
@brunapinos @leticiadesouza  @guiaugusto  finalizei a primeira versão do Forms. Acredito que os critérios de aceitação estão bem intuitivos.

A ideia que tive seria de apenas informar ao usuário o que ele deveria fazer ("ah, pede um cardápio do dia do RU") e a partir daí coletar os dados específicos. Não acho interessante fazer um teste "puramente guiado" pois poderia trazer respostas enviesadas. 

Aceito feedbacks! :)

https://docs.google.com/forms/d/e/1FAIpQLSdzU61s3buvne0DNDUoyK6MOGBZk5jro4keFvLyi2li37pk5w/viewform

PS.: Ainda não está publicado, farei após as respostas de vocês.

**Comment by guiaugusto** [comment]
Opa @icarooliv ...
Demorei mas tô aqui pra comentar!
Gostei muito do estado atual do forms, mas gostaria de dizer algumas coisas que talvez sejam boas pro processo:

1. Relacionado aos erros fatais, seria legal uma explicaçãozinha básica sobre o que significa e um campo onde o tester pode dar um feedback mais específico em formato de texto... Ajuda à quem está testando o bot a nos dar um feedback mais preciso sobre o problema apresentado.

2. Seria legal abranger todos os pontos aos quais estamos propondo entregar, não? Faltam:
- documentos
- cardápio semanal

Também seria legal tratar uma conversa aleatória com o bot, pro tester reportar o comportamento do bot diante de uma discussão aleatória.

No mais, acredito que seja só isso mesmo, o resto tá agradável e rápido de entender! Mandou bem!

**Comment by icarooliv** [comment]
> Relacionado aos erros fatais, seria legal uma explicaçãozinha básica sobre o que significa e um campo onde o tester pode dar um feedback mais específico em formato de texto... Ajuda à quem está testando o bot a nos dar um feedback mais preciso sobre o problema apresentado.

Nesse caso, quem está preenchendo o formulário não é o testador e sim um avaliador (a.k.a nossa equipe). Um exemplo de erro fatal seria ativar algum gatilho de confusão e o bot não completar a tarefa solicitada.


> Seria legal abranger todos os pontos aos quais estamos propondo entregar, não? Faltam:

Sim! Isso é interessante e vou colocar. A ideia seria homologar com vocês o modelo e depois especificarmos melhor as funcionalidades etc. A ideia é ser um teste rápido para que consigamos obter uma amostra razoável para analisar os dados depois.

**Comment by icarooliv** [comment]
Conforme foi conversado com o time pelo Telegram, o template foi aprovado e vamos começar a testar. Pra isso, será aberta uma nova issue para acompanhamento da atividade.
