### ISSUE TITLE
Refatoração de intents, stories e utters

### ISSUE THREAD

**Issue by MatheusBlanco** [fga-eps-mds/2018.2-Lino#149]
Refatoração de intents, stories e utters

Essa issue tem como objetivo refatorar o fluxo atual do bot, adicionando mais exemplos em cada intent para melhor compreendimento do usuário, adequação dos paths das stories para que o bot consiga fluir pelas conversas de maneira mais intuitiva e natural e reescrita das utters para que o fluxo de conversa permaneça limpo e agradável para o usuário.

**Tarefas**

- [x] Adicionar mais exemplos de frases nas intents
- [x] Rearranjar os paths das stories para melhor fluxo de conversa
- [x] Reescrever as utters para que o bot responda de maneira mais limpa e agradável de se ler

**Critérios de Aceitação**

- [x] Fluxo de conversa mais intuitivo e natural

**Comment by gabrielfilipe7unb** [comment]
As modificações necessárias foram feitas e issue foi resolvida. Porém, coincidentemente outra dupla de pareamento está resolvendo a issue do calendário e afim de evitar problemas ela não será modificada por hora.
