### ISSUE TITLE
Adicionar código de conduta para o projeto

### ISSUE THREAD

**Issue by guilacerda** [fga-eps-mds/2018.2-Lino#15]
**Descrição**
Adicionar código de conduta para o contribuidor do projeto seguir e padronizar todo tipo de contribuição.

**Atividades**
- [x] Estudar tipos de contribuições no contexto do projeto
- [x] Criar um código de conduta padronizado à comunidade de _software_ livre.

**Comment by icarooliv** [comment]
Adicionados! =)
