### ISSUE TITLE
[Task 3] US02 - Enviar cardápio semanal para o Facebook

### ISSUE THREAD

**Issue by guiaugusto** [fga-eps-mds/2018.2-Lino#150]
Task 3 - Enviar cardápio semanal através de mensagens para o usuário cadastrado no Facebook

**Descrição**

Criar método de envio de cardápio semanal para que todo usuário do bot no Facebook, que esteja cadastrado na notificação do cardápio semanal, receba o arquivo PDF relativo ao cardápio semanal.

**Tarefas**

- [x] Especificar método para envio do cardápio semanal aos usuários do Facebook.
- [x] Criar método para obtenção de usuários do banco específico do mensageiro.
**Critérios de Aceitação**

- [x] Usuário receber a notificação do cardápio semanal com o PDF relacionado, se registrado.
- [x] Código passando nos testes do flake8.

**Comment by guiaugusto** [comment]
Como já houve a finalização do envio do cardápio semanal aos usuários do Facebook, a issue foi fechada...
Foi feito o merge para a devel e foi testado através de uma interação com o BOT e a integração com o script dentro do container. Será necessário, posteriormente, organizar melhor o serviço de cronjob.

**Comment by leticiadesouza** [comment]
@guiaugusto melhorar o serviço do cronjob envolve novas tasks? viraria uma nova issue? Temos que ver qual o melhor momento pra priorizar

**Comment by guiaugusto** [comment]
Envolve sim, Letícia... Gostaria de resolver isso o mais cedo possível... Como entraria como refatoração, não entra no quesito de estimar pontuação, mas novas issues vão aparecer para corrigir o problema desse serviço. A necessidade de resolver isso cedo seria para já merjarmos tudo na master e forma estável, com todas as alterações significativas e criarmos uma nova release, tanto para o repositório do Lino quanto para os serviços.
