### ISSUE TITLE
[I13] US25 - Custom Action e fluxo de conversa para obtenção do cardápio do café da manhã

### ISSUE THREAD

**Issue by MatheusBlanco** [fga-eps-mds/2018.2-Lino#166]
US 25 - Custom Action e fluxo de conversa para obtenção do cardápio do café da manhã

Esta issue tem o objetivo de adicionar ao funcionamento do Lino a possibilidade de buscar, no WebCrawler, e enviar ao usuário o cardápio diário do café da manhã, por meio da interação com intents.

**Tarefas**

- [x] Criar da custom action para envio do café da manhã
- [x] Conectar custom action com webcrawler ru
- [x] Criar fluxo para obtenção do café da manhã

**Critérios de Aceitação**

- [x] Usuário requisitar e receber o café da manhã do dia.

**Comment by pedro-prp** [comment]
A issue foi finalizada com sucesso, tivemos alguns percalços para tratar as excessões, como o final de semana, mas já foram devidamente tratados e todo o conteúdo desta Issue já se encontra mergado na devel.
