### ISSUE TITLE
Criar um padrão de Contribuição

### ISSUE THREAD

**Issue by guilacerda** [fga-eps-mds/2018.2-Lino#17]
**Descrição**
Guia para padronizar como as pessoas devem contribuir para o projeto.

**Atividades**
- [x] Padronizar a contribuição à projetos de _software_ livre
- [x] Guia para código
- [ ] Guia para documento

**Comment by icarooliv** [comment]
Guia para contribuição adicionado. 
Acredito que o template para contribuição pode ser unificado tanto para código quanto documentação. Ambos seguiriam as mesmas regras de código de conduta, política de pull requests etc...
O que acham?
