### ISSUE TITLE
US03 - Fluxo de envio das notificações tratado com botões

### ISSUE THREAD

**Issue by gabrielfilipe7unb** [fga-eps-mds/2018.2-Lino#170]
**Descrição**

O Lino deve entender as mensagens do usuário por meio de botões. Para isso deve-se configurar o fluxo de envio das notificações para ser tratado com o uso de botões.

**Tarefas**

- [x] Configurar o fluxo para a utilização de botões no Telegram.
- [x] Configurar o fluxo para a utilização de botões no Messenger.

**Critérios de Aceitação**

- [x] O Lino deve entender normalmente as mensagens com os botões no Telegram.
- [x] O Lino deve entender normalmente as mensagens com os botões no Messenger.
- [x] Deve-se passar pelos teste do flake 8.

**Comment by guiaugusto** [comment]
Como o resultado foi documentado e informado no PR #187 , e também validado em produção, estou fechando essa issue, como prova de finalização do processo. Pra quaisquer melhoras ou evoluções, é necessário a criação de uma outra issue especificando detalhadamente o processo.
