### ISSUE TITLE
US26 - Script de envio do cardápio diário do almoço

### ISSUE THREAD

**Issue by guilhesme23** [fga-eps-mds/2018.2-Lino#172]
US26 - Eu, como usuário, desejo receber o cardápio do almoço do RU para me informar

**Descrição**

Esta issue envolvem 3 Tasks modularizadas, que por decisão da equipe, optou-se por trabalhar apenas com uma issue relacionando a cada PR, tendo a finalidade de tratar o PR como uma funcionalidade nova adicionada ao bot. 
Nesta nova funcionalidade, será criado um script em python que tem como objetivo enviar as notificações relacionadas ao cardápio diário do almoço, porém, apenas aos usuários que desejam receber tais. Com isso, deverá ser feito a distinção dos usuários que querem receber tal notificação, separando por cada tipo de mensageiro e enviando separadamente à cada solicitante.
Para o agendamento ser bem realizado, existe a necessidade de criar um cron para realizar tal notificação para enviar o cardápio em todos os dias úteis da semana, às 10:30 da manhã.

**Tarefas**

- [x] Especificar método para o envio do cardápio do almoço aos usuários do Telegram.
- [x] Criar método de envio do cardápio do almoço aos usuários do Telegram.
- [x] Especificar método para o envio do cardápio do almoço aos usuários do Facebook.
- [x] Criar método de envio do cardápio do almoço aos usuários do Facebook.
- [x] Incrementar um novo cron ao crontab para definir o envio do cardápio do almoço, associando ao script que realizará tal associação.
- [x] Criar um arquivo em shell para executar o arquivo de script em python.

**Critérios de Aceitação**

- [x] Usuário do Telegram deve receber a notificação do cardápio do almoço, caso registrado.
- [x] Usuário do Facebook deve receber a notificação do cardápio do almoço, caso registrado.
- [x] Código passando nos testes do Flake8.

**Comment by guiaugusto** [comment]
Issue finalizada, contida dentro do serviço de notificação e com o envio às 10:30 da manhã.
