### ISSUE TITLE
Melhora no treinamento do Lino

### ISSUE THREAD

**Issue by guilhesme23** [fga-eps-mds/2018.2-Lino#180]
A Carla  deu uma ideia de melhora no treinamento do bot, que eles estão usando no bot do lappis.

A ideia é fazer algumas alterações no arquivo train.py para melhorar a classificação e o fluxo de conversa, as alterações seriam nas policies e em alguns parâmetros que melhorariam o desempenho do bot.

**Comment by guilhesme23** [comment]
Alguns trechos de código que a Carla passou:

```
TRAINING_EPOCHS = int(os.getenv('TRAINING_EPOCHS', 20))
BATCH_SIZE = int(os.getenv('BATCH_SIZE', 10))
VALIDATION_SPLIT = float(os.getenv('VALIDATION_SPLIT', 0.2))
CORE_THRESHOLD = float(os.getenv('CORE_THRESHOLD', 0.6))
MAX_HISTORY = int(os.getenv('MAX_HISTORY', 2))
```
```
keras_1 = KerasPolicy(
                 MaxHistoryTrackerFeaturizer(
                     BinarySingleStateFeaturizer(),
                     max_history=MAX_HISTORY
                     )
                 )
```
```
agent = Agent(domain_file, policies=[
            keras_1,
            MemoizationPolicy(max_history=MAX_HISTORY),
                                                    CustomFallbackPolicy(
                        fallback_action_name=FALLBACK_ACTION_NAME,
                        nlu_threshold=NLU_THRESHOLD,
                        core_threshold=CORE_THRESHOLD)])
```
```
training_data = agent.load_data(training_folder,augmentation_factor=20)

    agent.train(training_data, epochs=TRAINING_EPOCHS, 
                                batch_size=BATCH_SIZE,
                                validation_split=VALIDATION_SPLIT)
```

**Comment by guiaugusto** [comment]
Você chegou a fazer algum teste após o uso dessas melhoras?
Quais pontos você conseguiu enxergar que obtiveram uma melhora significativa?

Não sei como deve ter sido, mas talvez no nosso caso, como ainda existem poucas intents, talvez não fique tão perceptível... Mas com o incremento de novas nessa semana, talvez as coisas possam se tornar mais perceptíveis.

**Comment by icarooliv** [comment]
Foram feitas e testadas as sugestões. Melhorou bastante a interação do bot com o usuário, devido à classificação das intents. Legal! =)
