### ISSUE TITLE
Diferenciação entre maiúsculas e minúsculas

### ISSUE THREAD

**Issue by guilhesme23** [fga-eps-mds/2018.2-Lino#193]
**Descrição**
Hoje percebemos que o Lino por algum motivo estava diferenciando letras maiúsculas e minúsculas. Conversei com a Carla pra perguntar se o bot que eles estão desenvolvendo possui o mesmo comportamento, visto que estamos usando o mesmo pipeline do NLU. 
Segundo o que esta documentado na issue https://github.com/lappis-unb/rouana/issues/205 usando esse pipeline o bot não deveria fazer esse tipo de diferença então precisamos investigar o motivo disso.

**Comment by icarooliv** [comment]
Erro corrigido.
