### ISSUE TITLE
Erro ao envio do cardápio da semana no Telegram

### ISSUE THREAD

**Issue by guilhesme23** [fga-eps-mds/2018.2-Lino#194]
**Descrição**
Por algum motivo o bot não esta enviando o cardápio da semana certa, a api ja foi verificada e esta retornando o cardápio certo. O que foi imaginado é que provavelmente o rasa deixa a imagem salva em cache, a ideia então é tirar a utter da domain e criar uma custom action pra enviar o cardápio

**Comment by guiaugusto** [comment]
Como já foi feita a solução pra tal problema, vou fechar essa issue aqui como comprovação de finalização... Quaisquer futuros problemas, pode reabrí-la, se quiser! xD
