### ISSUE TITLE
Criar fluxo para /help

### ISSUE THREAD

**Issue by gabrielfilipe7unb** [fga-eps-mds/2018.2-Lino#196]
**Descrição**

Deve-se orientar e ajudar o usuário com as funcionalidades do Lino

**Tarefas**

- [x] Aplicar personalidade do Lino nos textos
- [x] Criar entidades relacionadas a recepção do usuário

**Critérios de Aceitação**

- [x] Conversa fluida com o usuário

**Comment by gabrielfilipe7unb** [comment]
Falta completar a intent.

**Comment by gabrielfilipe7unb** [comment]
Falta adequar a personalidade do bot nas utters

![Alt Text](https://media.giphy.com/media/8YZosdST06OyyXGTCN/giphy.gif)

**Comment by gabrielfilipe7unb** [comment]
![alt text](https://github.com/adam-p/markdown-here/raw/master/src/common/images/icon48.png "Logo Title Text 1")

**Comment by gabrielfilipe7unb** [comment]
![](https://media.giphy.com/media/7NM9q98jMvlmLFvmSe/giphy.gif)

**Comment by guiaugusto** [comment]
Como o processo já foi realizado, testado manualmente e validado, além de merjado na master, estarei fechando a issue.
Qualquer tipo de problema relacionado à esta issue, peço que crie outra, especificando de forma completa os problemas apresentados, e se possível referenciando a issue.
