### ISSUE TITLE
Criar fluxo para /start

### ISSUE THREAD

**Issue by gabrielfilipe7unb** [fga-eps-mds/2018.2-Lino#197]
**Descrição**

Deve-se introduzir o usuário às funcionalidades do Lino.

**Tarefas**

- [x] Aplicar personalidade do Lino nos textos
- [x] Criar entidades relacionadas a recepção do usuário

**Critérios de Aceitação**

- [x] Conversa fluida com o usuário

**Comment by guiaugusto** [comment]
Como o processo já foi realizado, testado manualmente e validado, além de merjado na master, estarei fechando a issue.
Qualquer tipo de problema relacionado à esta issue, peço que crie outra, especificando de forma completa os problemas apresentados, e se possível referenciando a issue.
