### ISSUE TITLE
Criar fluxo para ofensas

### ISSUE THREAD

**Issue by gabrielfilipe7unb** [fga-eps-mds/2018.2-Lino#198]
**Descrição**

Deve-se tratar as ofensas cometidas contra o Lino.

**Tarefas**

- [x] Aplicar personalidade do Lino nos textos
- [x] Criar entidades relacionadas a recepção do usuário

**Critérios de Aceitação**

- [x] Conversa fluida com o usuário

**Comment by gabrielfilipe7unb** [comment]
![](https://media.giphy.com/media/8YZosdST06OyyXGTCN/giphy.gif)

**Comment by gabrielfilipe7unb** [comment]
Falta padronizar a personalidade do Lino nessa utter.

![](https://media.giphy.com/media/ZxBoQvHcCqVHOAvJ42/giphy.gif)

**Comment by guiaugusto** [comment]
Como o processo já foi realizado, testado manualmente e validado, além de merjado na master, estarei fechando a issue.
Qualquer tipo de problema relacionado à esta issue, peço que crie outra, especificando de forma completa os problemas apresentados, e se possível referenciando a issue.
