### ISSUE TITLE
Criar fluxo de despedida

### ISSUE THREAD

**Issue by gabrielfilipe7unb** [fga-eps-mds/2018.2-Lino#200]
**Descrição**

Deve-se tratar a forma que o Lino está se despedindo.

**Tarefas**

- [x] Aplicar personalidade do Lino nos textos
- [x] Criar entidades relacionadas a recepção do usuário

**Critérios de Aceitação**

- [ ] Conversa fluida com o usuário

**Comment by guiaugusto** [comment]
Como o processo já foi realizado, testado manualmente e validado, além de merjado na master, estarei fechando a issue.
Qualquer tipo de problema relacionado à esta issue, peço que crie outra, especificando de forma completa os problemas apresentados, e se possível referenciando a issue.
