### ISSUE TITLE
US28 - Padronizar personalidade do Lino

### ISSUE THREAD

**Issue by leticiadesouza** [fga-eps-mds/2018.2-Lino#221]
US28 - Padronizar a personalidade do Lino

**Descrição**
Padronizar as utters para que as conversas do Lino mantenham a personalidade, de modo a melhorar a comunicação com o usuário. 

**Tarefas**
- [x] utter_help
- [x] utter_start
- [x] utter_default
- [x] utter_offense
- [x] utter_compliments
- [x] utter_greet
- [x] utter_thanks
- [x] utter_goodbye
- [x] utter_notifications
- [x] utter_documents 
- [x] actions_menu
- [x] actions_notifications
- [x] actions_documents
- [x] action_calendar
- [x] retirar utter_weekly_menu
- [x] retirar utter_gmail

**Critérios de Aceitação**
- [ ] Conversa fluida com o usuário
- [ ] Personalidade padronizada
- [ ] Múltiplas respostas para as utters

**Comment by icarooliv** [comment]
Parabéns! Está coerente com os resultados dos testes de usabilidade.
