### ISSUE TITLE
Arrumar o problema relacionado aos tutoriais da solicitação das documentações

### ISSUE THREAD

**Issue by guiaugusto** [fga-eps-mds/2018.2-Lino#226]
**Descrição**

Ao realizar o tutorial da solicitação da grade horária do aluno, comprovante de aluno regular e comprovante de matricula, o fluxo é interrompido com o seguinte erro:
![image](https://user-images.githubusercontent.com/26308278/48708003-69840580-ebe8-11e8-9682-502ebda99fa9.png)

É importante consertar para que o ambiente de produção seja corrigido!

OBS: Vale atentar que, apesar do comprovante de matrícula estar funcionando normalmente, também deve ser refatorado, pelo fato de existir a necessidade de apagar a branch associada à ele.

**Tarefas**

- [x] Corrigir problema relacionado ao tutorial da declaração de grade horária
- [x] Corrigir link relacionado ao tutorial do comprovante de matrícula
- [x] Corrigir problema relacionado ao tutorial da declaração de aluno regular

**Critérios de Aceitação**

- [x] Fluxo de tutorial para obter a declaração de grade horária enviar a imagem e os textos corretamente aos usuários.
- [x] Fluxo de tutorial para o comprovante de matrícula enviar a imagem e os textos corretamente aos usuários.
- [x] Fluxo de tutorial para obter a declaração de aluno regular enviar a imagem e os textos corretamente aos usuários.
- [x] Código passando nos testes Flake8.

**Comment by icarooliv** [comment]
@guiaugusto O imgur tem uma API bem simples de utilizar, acho uma boa alternativa.

**Comment by pedro-prp** [comment]
Issue resolvida com êxito, era um problema simples de correção de um link inexistente.
