### ISSUE TITLE
Criar stickers para o pacote do grupo

### ISSUE THREAD

**Issue by guiaugusto** [fga-eps-mds/2018.2-Lino#228]
**Descrição**

Como enrolamos absurdamente pra fazer os sticker do grupo, tomei a iniciativa, com o respaldo do @guilacerda , de criar essa issue para alguém fazer. Precisamos dos nossos stickers para uma melhor interação com o grupo, e pra eu ficar mais contente também.

**Tarefas**

- [ ] Criar todos os stickers a partir da lista definida no comentário abaixo.

**Critérios de Aceitação**

- [ ] Stickers com qualidade e bem recortados.

**Comment by guiaugusto** [comment]
Por favor, alterem esse comentário aqui com ideias:
@guilacerda @leticiadesouza @icarooliv @brunapinos @gabrielfilipe7unb @braga9 @guilhesme23 @pedro-prp @MatheusBlanco 

Lista de sticker a serem feitos:

**Comment by guilacerda** [comment]
Se puderem passar as fotos por aqui, serei grato.

**Comment by gabrielfilipe7unb** [comment]
@guilacerda Sobre sticker

**Comment by gabrielfilipe7unb** [comment]
@guilacerda

**Comment by gabrielfilipe7unb** [comment]
@guilacerda

**Comment by gabrielfilipe7unb** [comment]
@guilacerda

**Comment by gabrielfilipe7unb** [comment]
@guilacerda

**Comment by gabrielfilipe7unb** [comment]
@guilacerda

**Comment by gabrielfilipe7unb** [comment]
@guilacerda

**Comment by gabrielfilipe7unb** [comment]
@guilacerda

**Comment by gabrielfilipe7unb** [comment]
![2018-11-20 18 13 59](https://user-images.githubusercontent.com/37154573/48800325-a4716080-ecf0-11e8-8499-62010007b1c3.jpg)
![2018-11-20 18 13 51](https://user-images.githubusercontent.com/37154573/48800328-a5a28d80-ecf0-11e8-9f0e-fca82f3b3ef3.jpg)
![2018-11-20 18 13 42](https://user-images.githubusercontent.com/37154573/48800329-a6d3ba80-ecf0-11e8-87cc-24cf72cb3a06.jpg)
![2018-11-20 18 13 38](https://user-images.githubusercontent.com/37154573/48800333-a89d7e00-ecf0-11e8-8b46-146cccb5fe74.jpg)
![2018-11-20 18 13 30](https://user-images.githubusercontent.com/37154573/48800335-a9ceab00-ecf0-11e8-809c-73e321d9f96c.jpg)
![2018-11-20 18 13 22](https://user-images.githubusercontent.com/37154573/48800338-aaffd800-ecf0-11e8-857b-563b2c344444.jpg)
![2018-11-20 18 13 13](https://user-images.githubusercontent.com/37154573/48800344-afc48c00-ecf0-11e8-8358-1694cbfe43d8.jpg)

**Comment by guiaugusto** [comment]
Caraca....
E esses stickers? Não vão sair não?
@gabrielfilipe7unb mó vacilão.... Colocou a foto de quando eu passei chapinha antes de cortar o cabelo xD

**Comment by gabrielfilipe7unb** [comment]
@guiaugusto Você é maravilhos de qualquer jeito bb *-*
