### ISSUE TITLE
Aprimorar o fluxo de trancamento de matrícula

### ISSUE THREAD

**Issue by guiaugusto** [fga-eps-mds/2018.2-Lino#233]
**Descrição**

Percebemos durante o ciclo de testes de Usabilidade que os fluxos de dúvidas relacionadas ao trancamento não estão intuitivos. O Lino não está explicativo e somente joga a informação (imagem) ao usuário, tornando-se desagradável, por não ser explicativo o suficiente sobre o tema abordado.

**Tarefas**

- [x] Aprimorar as mensagens associadas à intent com várias palavras chaves que sejam associadas ao calendário de matrícula.
- [x] Corrigir erros de português.

**Critérios de Aceitação**

- [x] Padrão de linguagem em português, de forma explicativa e sucinta.
- [x] Código passando pelos testes Flake8.

**Comment by gabrielfilipe7unb** [comment]
@guiaugusto Deixa comigo, bb!

**Comment by gabrielfilipe7unb** [comment]
Prontinho bb! 

![](https://media.giphy.com/media/psmj7c3DbrJKkbRYFj/giphy.gif)

**Comment by guiaugusto** [comment]
Mano, ficou top demais!
Muito completo e bem feitinho...
E agora, com a padronização feita ontem, vai ficar muito bem feito! Já pode enviar o PR lá xD
