### ISSUE TITLE
Refatorar documentos com o escopo da R2

### ISSUE THREAD

**Issue by leticiadesouza** [fga-eps-mds/2018.2-Lino#234]
Refatorar os documentos para a R2 de acordo com as mudanças realizadas no escopo.

**Descrição**
Ao longo da R2 o escopo do Lino sofreu diversas alterações relacionadas ao que responderia como funcionalidade ao usuário, sendo assim, faz-se necessário refatorar as documentações que ainda estão com o escopo antigo.

**Tarefas**
- [x] Refatorar EAP
- [x] Refatorar TAP
- [x] Refatorar Roadmap geral
- [x] Concluir Refatoração do Backlog do Produto

**Critérios de Aceitação**
- [x] Ter os documentos refatorados de acordo com o novo escopo.

**Comment by icarooliv** [comment]
Yay! Tudo atualizado =)
