### ISSUE TITLE
Refatorar documento de arquitetura do projeto

### ISSUE THREAD

**Issue by guiaugusto** [fga-eps-mds/2018.2-Lino#237]
Refatoração do documento de arquitetura com a inclusão de seus processos

**Descrição**

Será necessário realizar a refatoração do documento de arquitetura, realizando a inclusão de diversos processos que não foram previamente documentados e também modelando o formato atual da arquitetura do sistema.

**Tarefas**

- [x] Atualizar o novo estado dos serviços do projeto.
- [x] Corrigir eventuais erros atrelados.
- [x] Organizar imagens e diagramas para melhor orientar na explicação da arquitetura.

**Critérios de Aceitação**

- [x] Ter o documento criado e com um nível de entendimento alto.
- [x] Diagramas atualizados, bem orientados e facilmente entendíveis.
- [x] Documento na linguagem padrão da língua portuguesa.

**Comment by guilacerda** [comment]
Como o PR já está sendo feito e foi validado por parte da equipe, estarei fechando esta issue. Caso haja alguma nova alteração não prevista anteriormente, fique a vontade para reabrir a issue
