### ISSUE TITLE
Separar pasta de scripts do cronjob para fora da pasta Rasa

### ISSUE THREAD

**Issue by guiaugusto** [fga-eps-mds/2018.2-Lino#239]
**Descrição**

Existe um problema grande em manter a pasta de scripts dentro da pasta rasa do repositório. Fui relatado de confusões ao respeito de seu funcionamento, por aparentar estar atrelado diretamente ao Rasa. Logo, é necessário mover essas informações para fora da pasta Rasa, para melhor entendimento geral do funcionamento do Lino.

**Tarefas**

- [x] Mover pasta script para fora da pasta rasa.
- [x] Alterar informação da cópia dos scripts no Dockerfile do cronjob.

**Critérios de Aceitação**

- [x] Serviço do cronjob estar em funcionamento com os scripts associados.

**Comment by guilhesme23** [comment]
Como a refatoração já foi feita e merjada, vou fechar a issue.
