### ISSUE TITLE
Criar Documento de Visão

### ISSUE THREAD

**Issue by gabrielfilipe7unb** [fga-eps-mds/2018.2-Lino#24]
**Descrição**
Desenvolver o documento de visão relacionado ao projeto, seguindo o padrão UML.

**Tarefas**
- [x] Formatar com padrão UML;
- [x] Utilizar markdown;
- [x] Linguagem padrão pt_BR

**Comment by gabrielfilipe7unb** [comment]
Pessoal, estou precisando da lista de requisitos/prioridades para o desenvolvimento dos tópicos do documento.

**Comment by guilhesme23** [comment]
## Divisão dos tópicos
 - @MatheusBlanco - Tópico 1
- @braga9 - Tópico 2
- Eu - Tópicos 3, 8.4, 8.5 e 8.6
- @pedro-prp - Tópicos 4 e 5
- @gabrielfilipe7unb - Tópicos 6, 7, 8.1, 8.2 e 8.3

**Comment by guilacerda** [comment]
Galera, a issue será fechada. Cumpriu com o seu propósito, agora teremos uma nova para o refatoramento, pois agora com o escopo fechado serão mais claro os tópicos
