### ISSUE TITLE
Criar fluxos aleatórios para uma interação mais agradável

### ISSUE THREAD

**Issue by guiaugusto** [fga-eps-mds/2018.2-Lino#243]
**Descrição**

O Lino está muito objetivo, focando apenas na resposta das coisas que ele está preparado pra fazer. É legal, pra uma melhor interação com ele, criar fluxos aleatórios que façam ele ser mais interativo e descontraído, como o proposto pela personalidade dele.

**Tarefas**

- [x] Criar fluxos aleatórios para uma melhor interação.
- [x] Aprimorar os exemplos de cada fluxo para garantir o máximo de confiança.

**Critérios de Aceitação**

- [x] Mapear todos os fluxos como comentário desta issue (Falar brevemente cada um que foi adicionado).
- [x] Código passando pelo Flake8.

**Comment by guiaugusto** [comment]
Como tinha dito anteriormente, você consegue ver alguns fluxos aleatórios por esses links:

https://github.com/RocketChat/hubot-natural/blob/8b9681771be990752b7ed24f88c7ba29382726cb/training_data/corpus.yml#L304

https://github.com/RocketChat/hubot-natural/blob/1a60d89a5cf53eb5b2be1bd0ffd0f951e8caa5b1/training_data/catbot-en.yml#L1060

**Comment by gabrielfilipe7unb** [comment]
Pra já!

**Comment by icarooliv** [comment]
Iuhuuu!! Mais uma fechada! =)
