### ISSUE TITLE
Acrescentar negrito aos títulos do "/help"

### ISSUE THREAD

**Issue by pedro-prp** [fga-eps-mds/2018.2-Lino#245]
**Descrição**
Visto que o ''/help" possui muita informação, é necessário que os tópicos possuam uma divisão mais destoante, a qual será feita com a adição de negrito aos títulos de cada tópico.

**Tarefas**
- [ ] Adicionar tag de Bold as mensagens.
- [ ] Criar mecanismo que difere Telegram do facebook.
- [ ] Aplicar para os dois mensageiros simultaneamente.

**Critérios de Aceitação**
- [ ] Bold funcionando nos dois mensageiros
- [ ] Passando no Flake8

**Comment by brunapinos** [comment]
Não acho necessário, pois pode induzir o usuário a digitar palavras chaves

**Comment by icarooliv** [comment]
Pela decisão da equipe, não será refatorado esse fluxo com as tarefas descritas. Logo, será fechada essa issue.
