### ISSUE TITLE
BUG - Push para o repositório do dockerhub indevidamente quando na devel

### ISSUE THREAD

**Issue by guilacerda** [fga-eps-mds/2018.2-Lino#246]
**Descrição**
Há três estágios no deploy contínuo: Teste, build e deploy. 

Na devel é realizado o estágio de teste, como em qualquer branch, e o de build. Só que o estágio de build tem um subestágio que dá um push para o registry do Dockerhub. Porém não é o essencial fazermos isso porque aconteceu que nosso servidor caiu, quando o serviço voltou, ele pegou a imagem mais atual do dockerhub. E assim pegou uma atualização feita pela devel e não pela master.

É importante a branch devel rodar o estágio de build para vermos se está acontecendo algum erro com o docker e com o ambiente de deploy.

**Tarefas**
- [x] Alterar/criar o estágio de build da devel.

**Critérios de Aceitação**
- [x] A devel deverá apenas rodar a build e não dar push para o dockerhub

**Comment by guilacerda** [comment]
@guilhesme23 existe a possibilidade de fazermos o deploy de teste para o seu ambiente de deploy na Digital Ocean?

**Comment by guilhesme23** [comment]
@guilacerda Existe sim!

**Comment by guilacerda** [comment]
Foi consertado. Ainda foi feito um ambiente de homologação com stage de teste/build/deploy
