### ISSUE TITLE
Criar documento de arquitetura

### ISSUE THREAD

**Issue by guilacerda** [fga-eps-mds/2018.2-Lino#27]
**Descrição**

O Documento de Arquitetura de Software fornece uma visão geral de arquitetura abrangente do sistema, usando diversas visões de arquitetura para descrever diferentes aspectos do sistema. Logo fica como tarefa criar e elaborar um.

**Tarefas**
- [x] Criar documento e iniciar
- [x] Elaborar documento
- [x] Utilizar markdown;
- [x] Linguagem padrão pt_BR

**Comment by pedro-prp** [comment]
Alguém pode disponibilizar algum exemplo desse tipo de documento?

**Comment by brunapinos** [comment]
https://github.com/fga-eps-mds/2017.1-Trezentos/wiki/Documento-de-Arquitetura

**Comment by pedro-prp** [comment]
#### Ficou decidido que cada um fará um tópico:
* Pedro - tópico 1
* Gabriel Braga - tópico 2
* Gabriel Filipe - tópico 3
* Guilherme - tópico 4
* Blanco - tópico 5

**Comment by gabrielfilipe7unb** [comment]
Parte do tópico 3 já foi realizado, o que ainda não foi é consequência da falta de algumas informações. 

![Alt Text](https://media.giphy.com/media/9xjZfGoV4AXPKeHjBg/giphy.gif)

**Comment by MatheusBlanco** [comment]
@leticiadesouza , não consegui montar o tópico 5, a estrutura de pacotes, do documento de arquitetura. A Bruna pediu para falar contigo, que você poderia me ajudar.

**Comment by leticiadesouza** [comment]
meninos, amanhã no horário do almoço eu vou ajudá-los com a elaboração do diagrama de pacotes. Já combinei com o Matheus, mas quem mais quiser juntar, estaremos no ITRAC fazendo.

**Comment by gabrielfilipe7unb** [comment]
Esboço da parte de alertas: 
![image 2018-09-04 15 19 36](https://user-images.githubusercontent.com/37154573/45049741-ef66ca80-b055-11e8-9163-7ee235648726.jpg)
