### ISSUE TITLE
Criar quadro de conhecimento 

### ISSUE THREAD

**Issue by guilacerda** [fga-eps-mds/2018.2-Lino#29]
**Descrição**

Cria o quadro de conhecimento para acompanhar a evolução técnica dos membros da equipe.

**Tarefas**

- [ ] Definir as tecnologias (#30)
- [x] Criar e iniciar documento
- [x] Elaborar documento
- [x] Linguagem padrão pt_BR

**Comment by icarooliv** [comment]
Adicionado 

https://docs.google.com/spreadsheets/d/1R66MpS4hl9jqBj99va3lWRRBxNXWlcutqaqNq7McP04/edit?usp=sharing
