### ISSUE TITLE
Definir tecnologias

### ISSUE THREAD

**Issue by guilacerda** [fga-eps-mds/2018.2-Lino#30]
**Descrição**
Definir as tecnologias que serão utilizadas durante o semestre para desenvolver o projeto.

**Tarefas**

- [x] Entender o escopo do projeto
- [x] Entender a aplicabilidade do projeto
- [x] Pensar em um plano de ação para o desenvolvimento do projeto
- [x] Pensar nas tecnologias que serão utilizadas no projeto

**Comment by brunapinos** [comment]
Em uma discussão inicial, acho que as seguintes tecnologias e conhecimentos são relevantes:
- Rasa Core e NLU (para a construção do bot e processamento de linguagem natural);
- Telegram e Messenger (mensageiros)
- Docker (configuração do ambiente)
- Metodologia
- Pipeline de deploy continuo

**Comment by brunapinos** [comment]
Alguma coisa a acrescentar? @guiaugusto @guilacerda @leticiadesouza @icarooliv

**Comment by brunapinos** [comment]
Alguma coisa a acrescentar? @guiaugusto @guilacerda @leticiadesouza @icarooliv

**Comment by icarooliv** [comment]
Concordo com as apresentadas. Mas precisamos definir também as tecnologias de acompanhamento em uso, como sugerido pela Carla. O que acham de ElasticSearch e Kibana? Temos também que pensar no banco de dados, MongoDB parece interessante pra usar em conjunto com as outras duas tecnologias.

**Comment by brunapinos** [comment]
@icarooliv Esse site também faz analise. Talvez seja util 
https://www.dashbot.io/

**Comment by icarooliv** [comment]
@brunapinos, acredito que utilizar um painel pronto é interessante, mas precisamos verificar a viabilização  da ferramenta para a coleta de métricas interessantes para o projeto.

**Comment by guilacerda** [comment]
Concordo com as tecnologias sugeridas pela Carla em relação ao acompanhamento em uso

**Comment by brunapinos** [comment]
Decidido então o uso do ElasticSearch e Kibana
