### ISSUE TITLE
Elaborar plano de abertura de projeto (TAP)

### ISSUE THREAD

**Issue by guilacerda** [fga-eps-mds/2018.2-Lino#31]
**Descrição**

Criar o documento TAP. É a base do projeto e tem as principais informações para que qualquer pessoa que tenha contato com a empreitada consiga entender de uma vez suas principais particularidades.

**Tarefas**

- [ ] Versão inicial do TAP
- [ ] Formatação em markdown
- [ ] Linguagem padrão pt_BR

**Comment by brunapinos** [comment]
Acabou que a construção desse documento ficou prejudicada pela definição do escopo, mas acho que a @leticiadesouza e o @guiaugusto fizeram um esboço. Não foi isso?

**Comment by guiaugusto** [comment]
Foi sim @brunapinos ...

Mas ele está sendo adaptado e tá tendo um review do @icarooliv  para a avaliação da qualidade do documento.

Se você quiser ter um acesso mais por dentro, dá pra acompanhar por esse link:
<https://docs.google.com/document/d/1gNnJeEz4KNCeCol_b-L8nuEhY2KXR_vVedk3XGh48Oc/edit?usp=sharing>

Para a finalização do doc, os tópicos mais críticos são o de risco e de custo, que estão em andamento também. xD
