### ISSUE TITLE
Elaborar o backlog do produto

### ISSUE THREAD

**Issue by guilacerda** [fga-eps-mds/2018.2-Lino#32]
**Descrição**

Criar a versão inicial do _product backlog_. É uma lista contendo todas as funcionalidades desejadas do produto.

**Tarefas**
- [ ] Elaborar a versão inicial do backlog
- [x] Elicitar os requisitos do produto
- [x] Formatação em markdown
- [x] Linguagem padrão pt_BR

**Comment by icarooliv** [comment]
Para a Feature de Conversas, sugiro utilizarmos isso como guia: https://chatbotsmagazine.com/how-to-document-chatbot-requirements-7df81275cc66. O template de User Story não vejo como aplicável no nosso contexto.

**Comment by brunapinos** [comment]
@icarooliv Concordo. Como iremos usar o rasa como tecnologia e este segue o padrão de _intents_, _actions_, _utters_ e _entities_, acho que seria a melhor representação do conteúdo que o Lino irá servir
