### ISSUE TITLE
Refatoração do Bot (do treinamento)

### ISSUE THREAD

**Issue by guilacerda** [fga-eps-mds/2018.2-Lino#36]
**Descrição**

Os membros de MDS deverão fazer as alterações dos bugs encontrados e incrementar com o padrão de estilo PEP 8.

**Tarefas**

- [x] Corrigir os bugs encontrados e evoluir os fluxos criados;

- [x] Refatorar o código utilizando o padrão de estilo PEP  8;

**Links**

[Documentação PEP 8](https://www.python.org/dev/peps/pep-0008/)

**Comment by brunapinos** [comment]
@pedro-prp @guilhesme23 @braga9 @gabrielfilipe7unb @MatheusBlanco gostaria do feedback dessa issue. Sei que fizeram, mas quero manter o rastro dessas modificações.

**Comment by MatheusBlanco** [comment]
Eu, @braga9 e @gabrielfilipe7unb conseguimos melhorar um pouco o fluxo de conversa do nosso bot, mas tivemos dificuldade na implementação do serviço de localização, como dito na reunião do dia 02/09 pelo Gabriel Filipe

**Comment by guilhesme23** [comment]
Eu e o @pedro-prp arrumamos o bug que acontecia quando pesquisavam uma música que não existe no spotify, e colocamos o código no padrão pep8.

**Comment by guilacerda** [comment]
Acho que podemos dar por finalizado esse treinamento de bot para ambas equipes. Parabéns pelo resultado que tiveram!
