### ISSUE TITLE
US05 - Buscar informações sobre o cardápio do RU

### ISSUE THREAD

**Issue by guilacerda** [fga-eps-mds/2018.2-Lino#49]
US05 - Eu, como Lino desejo buscar as informações sobre o cardápio do RU na sua página oficial para para transferir a informação ao usuário solicitante.

**Descrição**
A issue é reponsável por ter como tarefa épica um webcrawler para que o Lino consiga buscar e fazer o download do cardápio, em formato PDF, no site oficial do RU.

**Tarefas**
- [x] Fazer um _webcrawler_ que consiga acessar o site oficial do RU.
- [x] Fazer com que o _webcrawler_ consiga acessar a página do cardápio no site.
- [x] Fazer com que o _webcrawler_ consiga fazer o download do PDF. 

**Critérios de Aceitação**
- [x] O sistema deve conseguir buscar e transformar o PDF 
- [x] Seguir políticas do repositório

**Comment by guilacerda** [comment]
Acho melhor  fragmentar a issue, como está exposto na imagem a baixo, o critério de aceitação informado cobre muito mais do que o exigido pela _issue_. Não condiz com a estimativa de pontos.

Será criada então uma nova issue para tal funcionalidade. #79

![image](https://user-images.githubusercontent.com/26297247/45654392-cdd3fd00-bab1-11e8-997c-2bb78a2f92d2.png)

**Comment by icarooliv** [comment]
História repontuada para 8 pontos, as issues derivadas para tasks (#79 e #92) não foram pontuadas/tiveram pontuação removida.
