### ISSUE TITLE
US08 - Comunicação entre o Lino e o Telegram

### ISSUE THREAD

**Issue by guilacerda** [fga-eps-mds/2018.2-Lino#50]
US08 - Eu, como Lino desejo me comunicar com os usuários pelo mensageiro Telegram para enviar mensagens a usuários dessa plataforma.

**Descrição**
Para que o Lino consiga se comunicar com os usuários, precisamos de uma plataforma intermediadora. Nosso primeiro caso é o mensageiro Telegram, onde está previsto uma parte do nosso público-alvo. 

Logo, precisamos que o bot consiga se comunicar primeiramente com a API do Telegram para que haja a interação com o usuário da plataforma.

**Tarefas**
- [x] Estudar API do Telegram
- [x] Fazer conexão entre o Lino e o Telegram

**Critérios de Aceitação**
- [x] O Lino está conectado ao Telegram

**Comment by gabrielfilipe7unb** [comment]
Fui pesquisar pra baixar o TensorFlow e vi que tem uma instalação com a virtualenv, quais as vantagens de baixar com ela?

**Comment by brunapinos** [comment]
Por enquanto, o modo para configurar o ambiente de vocês é usando o virtualenv, e este isola o ambiente python de sua máquina, evitando conflito de pacotes. Como vocês vão usar o ambiente python da virtualenv, é nele que se deve instalar o TensorFlow.

**Comment by brunapinos** [comment]
Para ajudar nessa issue, tem o repositório do Chatbot do Lappis
https://github.com/lappis-unb/chatops

**Comment by brunapinos** [comment]
Bot conectado com o Telegram, porém existe problemas com relação ao uso do bot (durante o desenvolvimento) por mais de uma pessoa
