### ISSUE TITLE
US22 - Definição da identidade visual do Lino

### ISSUE THREAD

**Issue by guiaugusto** [fga-eps-mds/2018.2-Lino#51]
US22 - Eu, como Lino desejo ter uma identidade visual para me mostrar ao mundo.

**Descrição**

Para estabelecer uma marca do produto, necessitamos decidir uma identidade visual ao Lino.
Na área de negócios, uma boa definição de identidade, além de uma boa escolha na tipografia e na paleta de cores, é essencial para criar uma marca impactante.

**Tarefas**

- [x] Encontrar a personalidade ideal para o bot no [site de personalidades](https://www.16personalities.com/br)
- [x] Definir paleta de cores
- [ ] Definir tipografia
- [x] Definir logo

**Critérios de Aceitação**

- [x] O Lino ter uma identidade visual definida

**Comment by brunapinos** [comment]
Na Sprint 2, o enfoque foi no fluxo e na personalidade do bot. Logo, apesar do logo, cores e tipografia terem sido estudados, a decisão foi de deixar essas escolhas para a Sprint 3
