### ISSUE TITLE
Criar DockerFile para desenvolvimento

### ISSUE THREAD

**Issue by guiaugusto** [fga-eps-mds/2018.2-Lino#53]
**Descrição**

O DockerFile é um documento que contém todos os comandos que o responsável pelo DevOps pode chamar na linha de comando para montar uma imagem para disponibilizar o ambiente de desenvolvimento do projeto.

**Tarefas**

- [x] Montar o Dockerfile para o ambiente do projeto

**Critérios de Aceitação**

 - [ ] Conseguir disponibilizar o serviço em ambiente de desenvolvimento

**Comment by guilacerda** [comment]
Agora é possível usar o docker para treinar o bot no terminal e pra utilizá-lo para desenvolvimento também (com o compose)

**Comment by icarooliv** [comment]
Devido a problemas pontuais nos ambientes de alguns membros, será preciso continuar com essa Issue aberta para a próxima Sprint, até que seja normalizado.
