### ISSUE TITLE
 Feedback Inicial - Issues e Documentação

### ISSUE THREAD

**Issue by fepas** [fga-eps-mds/2018.2-Lino#61]
Olá pessoas! A Carla me pediu pra dar um feedback dos grupos, e aqui estou! 

# Lino

- ## *Issues*

#### **Comunicação**

Vocês estão se comunicando bem nas *issues*, parabéns!

Se comunicar pelas *issues* trás uma comunicação bem transparente do projeto de vocês, e ajuda na avaliação de como vocês estão lidando com as adversidades de cada *issue*. É bem interessante que informações importantes estejam sempre sendo discutidas nas *issues*, além das outras ferramentas de comunicação que vocês usam, como *Telegram*.

#### **Pontuação**

Vocês estão utilizando bem as pontuações nas *issues*, aqui tem alguns links pra ajudar vocês ainda mais nisso:

- Detalhes sobre o método *Planning Poker*:

    http://www.metodoagil.com/planning-poker/

- Site para realizar o *Planning Poker* online:

    https://scrumpoker.online/

Eu particularmente prefiro fazer com *post-its*, mas vai da preferência da necessidade de cada grupo.

#### **Nomes**

As *issues* estão com bons nomes. É interessante a prática de padronizar os nomes, e vocês já fazem utilizando(em alguns casos não) os verbos no infinitivo (que já seria a minha recomendação). Está tudo bem claro e simples como deve ser.
Também é interessante a forma que vocês estão utilizando para mostrar que aquela *issue* é uma US. Nice! •ᴗ•

#### ***Labels***

As Labels também estão boas no geral. Provavelmente eu faça um mini-guia para ajudar outros grupos que estão mal nisso, mas definitivamente não é o caso de vocês. A suas são simples e cumprem seu papel.

As issues de vocês estão ótimas, bem nomeadas, bem explicativas, parabéns! (◕‿◕✿)

- ## Documentação

#### **Documento de Visão**

O documento de visão de vocês está bem claro em mostrar o que é o problema, seus desdobramentos, e a forma de atuação do Lino nesse problema.
Cumpre a função, está bem organizado e escrito, e o mais importante: simples, como deve ser.

#### **Documento de Arquitetura**

O documento de arquitetura bom no geral, senti a falta de alguns diagramas, como o de pacotes,
mas parece já estar planejado, então tá tudo *topper*. ◕‿◕

#### **Documentação Geral**

A Documentação de vocês tá muito bem organizada, fácil de encontrar e bem feita. Muito interessante a utilização do
quadro de pareamento, o burndown e a presença na daily, tudo muito bom.

- ## Considerações Finais

Que delicia de repositório, cara. ( ͡° ͜ʖ ͡°)

Vocês estão muito bem organizados, isso demonstra bastante a
maturidade do projeto de vocês. Tá tudo bem organizado, documentado e
explicado.

Uma dica:

- Assim que vocês definirem uma identidade visual, atualizem o README
com detalhes do projeto.

A Carla vai poder dar um feedback mais técnico pra vocês, mas espero ter ajudado na melhoria do
projeto de vocês de alguma forma. ( ⌒o⌒)人(⌒-⌒ )

[]s, @fepas

**Comment by guilacerda** [comment]
@fepas olha ai meus caros, estamos trabalhando bem! PARABENS PRA TODOS NÓSSSSS

**Comment by guiaugusto** [comment]
Valeu pelo feedback @fepas !

Vamos melhorar em questão de documentações... Essas ultimas sprints estão tendo seu tempo dedicado ao aperfeiçoamento e ao objetivo de completar elementos faltantes nos documentos.

Caso seja possível nos dar um feedback posteriormente, ficaríamos muito agradecidos!

Por ora, vou fechar a issue... Mas caso haja algum feedback a mais posteriormente, fique a vontade para reabrir e dar outro feedback!

Obrigadão!
