### ISSUE TITLE
Treinamento de Rasa

### ISSUE THREAD

**Issue by brunapinos** [fga-eps-mds/2018.2-Lino#7]
**Descrição**
Fazer um treinamento para a equipe de MDS de como construir um chatbot utilizando _framework_ **Rasa**.

**Atividades**
- [ ] Idealizar a apresentação
- [ ] Apresentar o Rasa
- [ ] Ensinar a construção de um exemplo simples

**Comment by guilacerda** [comment]
Acho melhor deixarmos pra mais tarde o treinamento do Rasa, em vista a evolução técnica na issue #9 dos membros de MDS

**Comment by brunapinos** [comment]
Ocorreu na Sprint 2, o início do desenvolvimento do bot e também a definição da arquitetura do projeto. Desse modo, uma explicação um pouco mais detalhada do funcionamento da tecnologia foi essencial, suprindo a função desse treinamento.
