### ISSUE TITLE
US07 - Comunicar o Lino com o mensageiro Messenger

### ISSUE THREAD

**Issue by guilacerda** [fga-eps-mds/2018.2-Lino#71]
US07 - Eu, como Lino desejo me comunicar com os usuários pelo mensageiro Messenger para enviar mensagens a usuários dessa plataforma.

**Descrição**

Esta issue é responsável por fazer uma comunicação entre o Lino e o Messenger, para que seja possível o usuário se comunicar com mais um mensageiro.

**Tarefas**
- [x] Estudar API do Messenger
- [x] Fazer conexão entre o Lino e o Messenger

**Critérios de Aceitação**
- [x] O Lino está conectado ao Messenger

**Comment by pedro-prp** [comment]
Seguindo a própria documentação do Rasa, a conexão com o Messenger pareceu ser tranquila de ser feita, a grande dificuldade é gerar um webhook, mesmo iniciando o bot em uma porta local e expondo essa porta local através do Ngrok, o facebook não reconhece como uma Url possível para ser feito o webhook. Graças a isso, todo a avanço fica travado, foram realizadas diversas pesquisas sobre problemas parecidos, mas nenhum tutorial de fato solucionou o problema.

**Comment by MatheusBlanco** [comment]
Para resolver o problema da Issue, ao invés de usarmos a própria base do bot para fazer as requests, fizemos um script por fora, utilizando a configuração do webhook fornecida pelo facebook. Utilizamos nodejs para a implementação deste script. Agora o facebook exige que o bot seja publicado para que possa funcionar, sendo que a publicação já está sendo processada. Faltando apenas a Url da política de privacide

**Comment by MatheusBlanco** [comment]
A conexão com o Messenger foi completada. Mas estamos com dúvida sobre como fazer o bot responder pelo facebook, e se isso também é parte da issue. @guilacerda @brunapinos

**Comment by guilacerda** [comment]
@MatheusBlanco Eu imagino que para ter certeza de que a conexão está funcionando haja um teste da funcionalidade, que no caso seria testar uma resposta do bot. O que acha @brunapinos?

**Comment by brunapinos** [comment]
@guilacerda Concordo. Pra isso temos que criar uma página para o Lino e fazer com a interação ocorre via chat dessa página

**Comment by pedro-prp** [comment]
@brunapinos A página ja foi criada, pois o messenger pede ela desde do princípio do projeto, ao tentar mandar uma mensagem ao lino, recebo um retorno no terminal, indicando que o server está se comunicando com o facebook, mas ele ainda não responde as interações.
![sem titulo](https://user-images.githubusercontent.com/32720946/45790470-68bc0b00-bc5b-11e8-9e21-122b51c7603c.png)
![feefeef](https://user-images.githubusercontent.com/32720946/45790588-eb44ca80-bc5b-11e8-9aa5-3f3ccccda925.png)

**Comment by pedro-prp** [comment]
Eu e o @MatheusBlanco já estamos dando olhada no channel input e output que consta na documentação do rasa, acho que falta a aplicação deles para o que o bot possa interagir de fato.

**Comment by MatheusBlanco** [comment]
Estamos tentando lançar o Lino pela plataforma do facebook, mas para isso precisamos de uma Url de Política de Privacidade. Criamos uma utilizando node js e html e a ativamos, entretanto o facebook developers ainda não a aceita.

**Comment by MatheusBlanco** [comment]
@guilacerda , os arquivos de política de privacidade já estão na branch, dentro do folder rasa, como pedido durante a daily.

**Comment by MatheusBlanco** [comment]
![57](https://user-images.githubusercontent.com/37380789/45900057-f9f2c500-bdb4-11e8-80f2-ef925613ddc8.jpg)
Bot funcionando no messenger
