### ISSUE TITLE
Evoluir a Arquitetura do Projeto

### ISSUE THREAD

**Issue by guiaugusto** [fga-eps-mds/2018.2-Lino#73]
**Descrição**

A issue consiste em mostrar as evoluções da arquitetura do sistema, assim como as estratégias utilizadas para cada ponto específico. Com a arquitetura inicialmente definida, existe a necessidade de uma evolução para ser melhor adaptada no projeto.

**Tarefas**

- [x] Criar fluxo de relações da arquitetura
- [x] Definir estratégias para cada ponto específico da arquitetura

**Critérios de Aceitação**

- [x] Confirmação das estratégias para os pontos do projeto
- [x] Criação de um Diagrama final para a arquitetura
- [x] Linguagem PT-BR

**Comment by guiaugusto** [comment]
Montei esse diagrama com base nas dúvidas que tirei com a professora Milene sobre a possível arquitetura do projeto.

Após uma conversa para definirmos de vez a arquitetura mais semelhante ao nosso contexto, conversamos e chegamos em um consenso de que, a partir do feedback da professora, uma arquitetura de repositório (sendo o core do Bot o próprio repositório) com os componentes sendo microserviços seria mais fidedigno ao que estávamos procurando, tendo um broker para intermediário do cliente - servidor abordado pelos microserviços, pois:

- Como alguns componentes do sistema possuem uma autonomia e independencia do bot, temos uma característica forte de um microserviço.
- Como há várias desvantagens com a arquitetura cliente-servidor, é possível minimizar intensamente com o uso do broker para barramento de mensagens, com a tecnologia RabbitMQ.

Segue, abaixo, a imagem da primeira versão do diagrama após análise do feedback da professora.

![diagrama de relacoes](https://user-images.githubusercontent.com/26308278/45523226-85a99780-b79e-11e8-8a6c-4e5da43953b7.jpg)

**Comment by guiaugusto** [comment]
@icarooliv ...
Sobre o diagrama, você tinha mencionado algo anteriormente, sobre a necessidade de trabalhar com os dados que são encaminhados ao banco... Você poderia dar usa ideia aqui?

**Comment by guiaugusto** [comment]
Para estratégias relacionadas ao Broker, será tratado tudo na issue #69

**Comment by icarooliv** [comment]
@guiaugusto, minha preocupação seria com a API do Telegram e do Messenger tratando diretamente com o banco de dados. Acredito que isso não é seguro, e nem possível. O ideal seria uma API para gerenciar as requisições após o barramento de mensagens pelo RabbitMQ.

**Comment by guiaugusto** [comment]
Mas assim, @icarooliv ...
Se não me engano, o Rasa parece fazer essa comunicação interna por barramento de mensagens também, pelo o que eu consegui identificar com o @guilhesme23 ...
Apesar de existir, não seria válido inserir como parte do comunicador... Pra mim, isso estaria intrínseco dentro do componente Lino...
Sobre a API pra tratar o log de conversas, concordo contigo. É importante ter. Irei remodelar e colocar aqui pra ver se aparenta melhor com o que você estava pensando.

**Comment by guiaugusto** [comment]
Seria melhor dessa forma?

![diagrama de relacoes - versao 2](https://user-images.githubusercontent.com/26308278/45591385-b7019f00-b927-11e8-99c8-514aa2d781c1.png)

As APIs de tratamento desse tipo de informação só iria ter suas informações consumidas pelo banco, não havendo uma necessidade de integração bilateral. É a ideia inicial, mas ainda é bom ter mapeado isso.

**Comment by guiaugusto** [comment]
Quanto as estratégias, após a conversa que rolou no DOJO de hoje, decidi manter uma fila única de mensagens para cada tipo de informação, ou seja, uma fila para as informações maturadas pelo WebCrawler (podendo ser facilmente adaptada com uma fila correspondente a cada tipo de informação a ser tratada, por exemplo, uma fila para o cardápio, uma fila para as informações de estágio, etc), usando o padrão RCP para envio e recuperação de mensagens entre cliente-servidor.

Conversei apenas com o @guilhesme23 e o @braga9  sobre isso... Mas foi o que me aparentou a melhor estratégia.

Para entender melhor o contexto, se seguir a issue #69, eu deixarei um link para visualização do slide do dojo, pra entender o processo de criação de arquitetura, além de uma explicação mais aprofundada da definição das estratégias do RabbitMQ...

Além disso, sobre a arquitetura em si, existe a necessidade de começar a montar os microserviços separadamente para o prosseguimento das outras atividades, pois a separação de repositórios e a orquestração dos containeres é de grande importância para o bom andamento. Tivemos um andamento na reunião de hoje, que pode nos ajudar na criação da comunicação entre os microserviços.

**Comment by guiaugusto** [comment]
Por fim, chegamos a conclusão na seguinte arquitetura, levando em conta os pontos apresentados como fraqueza em nossa modelagem, ajeitando outros problemas que não tinhamos mitigado por completo.

![diagrama de relacoes 2](https://user-images.githubusercontent.com/26308278/46155321-6b1af800-c24d-11e8-8c3e-7ce6fa949db4.jpg)
