### ISSUE TITLE
API Gmail Dica

### ISSUE THREAD

**Issue by arthurbdiniz** [fga-eps-mds/2018.2-Lino#76]
Eae glr, sei que vão precisar conversar com a API do gmail. 

Já fiz alguns trabalho utilizando outras API do google e elas seguem o mesmo caminho. Uma dica é que a próprio google disponibiliza uma documentação muito boa para fazer isso e pode ser encontrada nesse [link](https://developers.google.com/gmail/api/guides/).

Tem alguns exemplos já prontos no canto esquerdo em várias linguagens e uma série de referencias sobre a api que é so mudar a rota e rodar o programa. 

![image](https://user-images.githubusercontent.com/18387694/45602818-154b8200-b9fb-11e8-838b-455a8889070d.png)

Qualquer duvida sobre, só me marcar nessa issue ou me enviar mensagem no telegram no @arthurbdiniz que eu estarei disponível  👍🏼

**Comment by guiaugusto** [comment]
Eita @arthurbdiniz ...
Ter sua ajuda vai ser muito bom pra conseguirmos andar com essas issues... Vamos procurar, primeiramente, estudar nosso problema para tirarmos dúvidas específicas sobre a comunicação com essa API... Obrigado pelo apoio <3

**Comment by guiaugusto** [comment]
Obrigado pela ajuda em relação a comunicação da API do Gmail @arthurbdiniz ... Conseguimos obter um progresso legal que acabou resultando em um bom serviço que terá um incremento significativo na finalidade do nosso bot... Obrigadão!
Com isso, vou fechando essa issue aqui... Qualquer dica ou ajuda que queira dizer, tem a total liberdade de reabri-la!
