### ISSUE TITLE
Entrevistas abertas com funcionários técnicos

### ISSUE THREAD

**Issue by brunapinos** [fga-eps-mds/2018.2-Lino#8]
**Descrição**
Fazer entrevista abertas com Coordenadores, professores, secretários, para levantar necessidades com relação ao atendimento a alunos.
**Atividades**
- [x] Decidir funcionários que serão entrevistados
- [x] Decidir maneira de formalizar os anseios (enquete, Google Forms, ...)
- [ ] Aplicar entrevista

**Comment by leticiadesouza** [comment]
**Possíveis Entrevistados do dia 22/08**
- Professora Paula Meyer 
- Professor Thiago Alves
- Secretaria
- UnB Idiomas

**Comment by guiaugusto** [comment]
Para uma melhor elicitação, é uma boa ideia conversarmos com os coordenadores de cada curso, para entender o que os alunos mais perguntam em relação à faculdade.

**Comment by leticiadesouza** [comment]
**Pautas da Entrevista:**

**  Perguntas mais gerais ** 
- Quais são as perguntas mais frequentes feitas por parte dos alunos? 
- Existem sites que podem auxiliar os estudantes na retirada de algumas dúvidas? 
- Quais as perguntas frequentes sobre o desligamento? Aonde os alunos conseguem informações sobre essa pauta?  

**Coordenador Específico do Curso**
(Sobre Matrículas)
- Existe uma grande demanda sobre matrículas fora do período de ajustes de matrícula?
- Existe algum meio de informação sobre os períodos de matrícula de fácil acesso?

** Coodenador de Estágio Supervisionado ** 
- Existe, em algum site/veículo de informação, detalhes sobre as documentações e informações necessárias para a matrícula em Estágio Supervisionado?
- 

** Secretaria **
- Existe algum meio onde se possa encontrar os horários de funcionamento da secretaria?
- Quais as documentações necessárias para adquirir documentos específicos (comprovantes de matrícula, diplomas, etc)?
- Quais tipos de documentos podem ser emitidos pela secretaria?

**Comment by leticiadesouza** [comment]
Massa! A gente pode pesquisar algum estilo de questionário específico, que seja mais adequado pro tipo de resposta que a gente quer, pra ajudar mais ainda na hora de levantar os requisitos. Vou dar uma pesquisada sobre isso e colo alguns links aqui!

**Comment by guilacerda** [comment]
Em qual status ta a issue? @leticiadesouza e @guiaugusto

**Comment by guiaugusto** [comment]
Essa issue foi fechada a um bom tempo na verdade kkk...

De um jeito formal, entrevistamos:

- Secretaria
- UnB Idiomas

De uma forma mais como conversa e para tirar dúvidas, aproveitamos que eu já havia conversando anteriormente com o coordenador de estágios de Software, Thiago Alves, para pegarmos o fluxo de matrícula no estágio para filtrarmos as documentações necessárias para esta ação... E como nosso backlog abrange mais esse contexto, optamos por fazer uso de entrevistas mais formais que serão documentadas na branch de entrevistas, organizadas em atas nas atas gerais.

É claro que entrevistamos outras pessoas, mas falta documentar dentro das atas de reuniões gerais e dentro da branch de entrevista.

Em relação ao questionário, tá tudo documentado no padrão das perguntas realizadas, qualquer dúvida sobre a organização, pode perguntar pra mim ou pra @leticiadesouza , que a gente explica com mais detalhes (apesar de eu não achar necessário)
