### ISSUE TITLE
US01 - Criar script de notificação do cardápio

### ISSUE THREAD

**Issue by guiaugusto** [fga-eps-mds/2018.2-Lino#87]
US01 - Eu, como usuário, desejo ser notificado sobre o cardápio diário do RU para me informar

**Descrição**

É necessário que exista um script para enviar as notificações relativas ao cardápio diário aos usuários que desejam recebê-lo.

**Tarefas**

- [x] Construir mensagem a partir do JSON recebido pelo WebCrawler
- [x] Realizar conexão com o banco para pegar os usuários cadastrados
- [x] Criar script que envia o cardápio formatado aos usuários cadastrados no banco

**Critérios de Aceitação**

- [x] O Lino deve enviar o cardápio aos usuários cadastrados

**Comment by pedro-prp** [comment]
Bom, essa Issue ta sendo bem complicada e mesmo depois do pareamento extenso de terça(25/09) ainda não havia sido encontrado uma solução. Hoje quarta(26/09) tivemos a ideia de não utilizar o Rasa para as notificações, manter ele para tratar o NLU e toda parte da conversação, mas para as notificações iremos utilizar um server em python que tbm se conecta ao Lino. Testamos em um bot genérico e conseguimos aplicar o POST para simular o bot enviando uma mensagem, com isso poderíamos programar esse comando de post com o Cronjob e fazer ele enviar aos usuários as notificações na hora certa.

**Comment by guiaugusto** [comment]
Isso é bom, @pedro-prp ... Eu dei uma analisada melhor e, pela dificuldade envolvida na história, resolvi dividir em 3 issues.

1. Seria em torno da ideia de criar o script para comunicação com o bot, como essa que já foi feita;
2. Criar o cronjob que envia as notificações aos usuários em determinado tempo; e
3. Fazer com que os id dos novos usuários sejam salvos no banco de dados (Criar uma action para isso).

No caso, também reveria as pontuações, sendo que:

* Para a primeira, 5 pontos, pela dificuldade técnica encontrada
* Para a segunda, 2 pontos
* Para a terceira, 8 pontos, pelo fato de parte do nosso estudo ontem(25/09) foi mais dedicada a isso, onde ainda não conseguimos encontrar uma solução para o problema.

O que acha? @pedro-prp @guilhesme23

**Comment by guilhesme23** [comment]
@guiaugusto Acho uma boa!

**Comment by pedro-prp** [comment]
@pedro-prp pra mim está perfeito essa nova organização.

**Comment by guilhesme23** [comment]
O script acabou de ser finalizado, agora ao rodar o script o Bot envia o cardápio completo do dia para os usuários com o id do Telegram cadastrado no banco.
