### ISSUE TITLE
Intent_01 - Iniciar sessão do bot

### ISSUE THREAD

**Issue by guilacerda** [fga-eps-mds/2018.2-Lino#88]
**Descrição**
Montar o fluxo de iniciação de conversa. É o primeiro contato com o usuário, recepção.

**Tarefas**
- [x] Aplicar personalidade do Lino nos textos
- [x] Criar entidades relacionadas a recepção do usuário

**Critérios de Aceitação**
- [ ] Conversa fluida com o usuário

**Comment by MatheusBlanco** [comment]
Depois de resolver alguns problemas em relação à formatação, que estava quebrando o Docker e impedia o bot de funcionar, acreditamos ter terminado finalmente a issue, aplicando a personalidade do lino nos textos e arrumando a formatação de acordo com a style sheet
