### ISSUE TITLE
Criação de um bot no Telegram 

### ISSUE THREAD

**Issue by icarooliv** [fga-eps-mds/2018.2-Lino#9]
**Descrição**

Propor uma atividade pra MDS relembrar e praticar os conceitos de git, Python e como funciona a API do Telegram para criação dos bots.

**Atividades**
**SPRINT 0**
- [x] Criar um bot no Telegram e obter um token no BotFather;

- [x] Codificar, em Python, o backend para o bot criado e enviar uma mensagem "Hello World!" para o usuário do bot; 

- [x] Subir o código em uma branch "devel" em um repositório remoto no GitHub

**SPRINT 1**
- [ ] Corrigir os bugs encontrados e evoluir os fluxos criados;

- [ ] Refatorar o código utilizando o padrão de estilo PEP  8;

**Links**

[Como criar um chatbot para Telegram](https://blog.mbeck.com.br/como-criar-um-chatbot-para-telegram-81a556cc0e52)

[Repositório de bots feitos em TecProg 2018/1](https://github.com/TecProg-20181/Taskbot)

[Documentação Telegram](https://core.telegram.org/bots#6-botfather)

[Documentação PEP 8](https://www.python.org/dev/peps/pep-0008/)

**Comment by guilhesme23** [comment]
### Repositório de teste do Bot
https://github.com/guilhesme23/chiquinBot

**Comment by MatheusBlanco** [comment]
**Repositório de teste do outro bot**
https://github.com/MatheusBlanco/oBot.git

**Comment by icarooliv** [comment]
Parece que subestimei vocês... hahaha. Parabéns, galera!! 

A issue vai permanecer aberta para outros "desafios" que virão a partir do próximo sábado!

**Comment by gabrielfilipe7unb** [comment]
https://github.com/gabrielfilipe7unb/LombraBot

![Alt Text](https://media.giphy.com/media/26u42gAFROFb0VyCI/giphy.gif)

**Comment by icarooliv** [comment]
Pessoal, deem uma olhada no OP pois adicionei novas atividades pra essa sprint!
