### ISSUE TITLE
Criar o pipeline de deploy do Lino

### ISSUE THREAD

**Issue by guilacerda** [fga-eps-mds/2018.2-Lino#94]
**Descrição**
Criar um pipeline para que quando acontecer uma alteração em determinada branch em um repositório remoto, o Lino seja atualizado em deploy e/ou homologação.

**Tarefas**
- [x] Utilizar o Gitlab-CI
- [x] Utilizar o Registry do Gitlab
- [x] Utilizar o Rancher

**Critérios de Aceitação**
- [x] O processo de deploy está automatizado

**Comment by guilacerda** [comment]
Ao contrário do planejamento, foi decidido utilizar o DockerHub ao invés do Registry do Gitlab.

Além do mais, proponho novas tasks para a issue:

- [ ] Adicionar stages de build/deploy para o Telegram
- [ ] Adicionar stages de build/deploy para o Messenger

**Comment by guilacerda** [comment]
A conexão entre o bot e o banco que vai guardar estava com problema de conexão. O problema foi identificado e resolvido apenas por problema de sintaxe e de ambiente

**Comment by brunapinos** [comment]
Qual é a situação da issues? @guilacerda

**Comment by guilacerda** [comment]
O deploy está funcionando corretamente para o ambiente do Telegram. Só que como ainda estamos com problemas de conectividade com o Messenger, o mesmo não encontra-se concluído.

**Comment by guilacerda** [comment]
Amanhã na sexta-feira eu, o @guilhesme e o @guiaugusto vamos fazer a integração contínua do facebook e terminar de conectar os serviços, tanto no Telegram, quanto no facebook.
